// react-blog/src/pages/Home.js

import React from 'react'
import { useEffect } from 'react'
import { useNavigate , useLocation} from 'react-router-dom'
import { useState ,useLayoutEffect} from 'react'
import './Home.css'

function Home() {
    
    const [list , setList] = useState([])
    const navigate = useNavigate()
    useLayoutEffect(()=>{
        const AV=require('leancloud-storage')
        AV.init({
            appId: "pTtwtgVghMG7r3ReP8EkNEEI-gzGzoHsz",
            appKey: "vky0hDUeQiaK50ay78CsgMBz",
            serverURL: "https://pttwtgvg.lc-cn-n1-shared.com"
        })
        const query=new AV.Query('blog')
        query.lessThan('id',300)
        query.find().then((blogs)=>{
            const list1 =[]
            for(var i=0;i<blogs.length;i++){
                var newContent = {id:blogs[i].attributes.id,content:blogs[i].attributes.content,headline:blogs[i].attributes.headline,eid:blogs[i].id}
                list1.push(newContent)
            }
            console.log(list1)
            setList(list1)
        })
    },[])
       function NewBuild(){
        navigate('/NewBuild')
        }

        function Showcontent(blogs){
            
            navigate('/ShowContent',{state:{item:blogs}})
        }
        return(
            <div>
                <ul>
                {list.map((blogs,index)=>{
                     return <div key={index} className='homeContent'onClick={()=>Showcontent(blogs)}>{blogs.headline}</div>
                }
                    
                )}
                </ul>
                <button onClick={NewBuild}>新建</button>
            </div>
        )
            }


export default Home

// blog/src/components/Home.vue
<template>
<div class='wee'>
  <button @click="newbuilt">新建博客</button>
  <div class="ep">
  <h2 v-for="item in this.list" v-bind:key="item"><a @click="shower(item)">{{item.attributes.headline}}</a><br/><br/><button @click="delt(item.id)">删除</button><button @click="revi(item)">修改</button></h2>
  <button @click="show">123</button>
  </div>

</div>
</template>

<script>
export default {
  name: 'App',
  data(){
    return{
      list:{}
    }
  },
  components: {
  },
  methods:{
    show(){
      const AV = require('leancloud-storage');
      AV.init({
          appId: "pTtwtgVghMG7r3ReP8EkNEEI-gzGzoHsz",
          appKey: "vky0hDUeQiaK50ay78CsgMBz",
          serverURL: "https://pttwtgvg.lc-cn-n1-shared.com"
        });
      const query=new AV.Query('blog');
      query.lessThan('id',300);
      query.find().then((blogs)=>{
        console.log(blogs)
        this.list=blogs
      })
      console.log(this.list)
    },
    newbuilt(){
      
      this.$router.push({path:'/Newbuilt'});
    },
    delt(id){
      const AV = require('leancloud-storage');
      AV.init({
          appId: "pTtwtgVghMG7r3ReP8EkNEEI-gzGzoHsz",
          appKey: "vky0hDUeQiaK50ay78CsgMBz",
          serverURL: "https://pttwtgvg.lc-cn-n1-shared.com"
        });
      const todo = AV.Object.createWithoutData('blog', id);
       todo.destroy();
    },
    revi(item){
      this.$router.push({
        path:'/Revise',
        query:{
          "id":item.id,
          "headline":item.attributes.headline,
          "content":item.attributes.content
        }
        })
    },
    shower(item){
      this.$router.push({
        path:'/Show',
        query:{
          "id":item.id,
          "headline":item.attributes.headline,
          "content":item.attributes.content
        }
        })
    },
  },
}
</script>

<style>
.ep{
  width: 61.8%;
  height:700px;
}
.wee{
  display: flex;
  justify-content: center;
  width:100%;
}

</style>
